perf(core): Fixing ristretto cache to pass jepsen tests
hypermodeinc/dgraph pull request #9237
Opened 2024-12-09 05:43 UTC by harshil-goel

Title format:

 - `Topic(Area): Feature`
 - `Topic` must be one of `build|ci|docs|feat|fix|perf|refactor|chore|test`
 - `Area` must be one of `acl|audit|backup|badger|cdc|dql|export|graphql|indexing|multi-tenancy|raft|restore|upgrade|zero`
 - * Add [BREAKING] if it is a breaking change

------------------
Body Format:

Description: <add description>
Fixes: <GitHub Issue>
Closes: <JIRA Issue>
Docs: <docs PR>

2025-01-02 10:28 UTC, harshil-goel commented on worker/sort_test.go
> +func RandStringBytes(n int) string {
rand

2025-01-02 11:14 UTC, harshil-goel commented on posting/mvcc.go
> +func (ml *MemoryLayer) saveInCache(key []byte, l *List) {
Leave a comment saying that ensure that ti's the latest data written on disk

2025-01-02 11:18 UTC, harshil-goel commented on posting/mvcc.go
> +		ml.del([]byte(key))
TODO. Comment

2025-01-06 18:12 UTC, mangalaman93 requested changes

2025-01-06 18:12 UTC, mangalaman93 commented on posting/mvcc.go
> +	go func() {
stop the goroutine when alpha stops

2025-01-06 18:12 UTC, mangalaman93 commented on posting/mvcc.go
> +	if cacheSize > 0 {
initMemoryLayer is only called when cacheSize is > 0

2025-01-06 18:12 UTC, mangalaman93 commented on posting/mvcc.go
> +func (ml *MemoryLayer) get(key []byte) (*CachePL, bool) {
fix the name of the param

2025-01-06 18:12 UTC, mangalaman93 commented on posting/mvcc.go
> +	if deltaCount > 500 {
have we set deltacount back to 0?

2025-01-06 18:12 UTC, mangalaman93 commented on posting/mvcc.go
> +		ml.numCacheRead += 1
move this inside a Cache object

2025-01-07 09:13 UTC, harshil-goel commented on posting/list.go
> +func (mm *MutableLayer) setTs(readTs uint64) {
It's exposed. I just made it for the nil check to be made easy.

2025-01-07 09:58 UTC, harshil-goel commented on posting/index.go
> +		memoryLayer.del(key)
Why delete everything when can delete just the requried keys.

2025-01-07 09:58 UTC, harshil-goel commented on posting/index.go
> +		memoryLayer.del(key)
Why delete everything when can delete just the requried keys. The cache value would get used to create the new value instead of reading from the disk this way.

2025-01-07 10:01 UTC, harshil-goel commented on worker/draft.go
> +		posting.ResetCache()
Yes

2025-01-08 08:06 UTC, mangalaman93 approved these changes

2025-01-13 08:46 UTC, mangalaman93 approved these changes

2025-01-13 08:46 UTC, merged

2025-01-13 08:50 UTC, mangalaman93 commented on dgraph/cmd/alpha/run.go
> +		Flag("keep-updates",
delete-on-update

On true, we delete the key from cache when an update is made to the same key. Otherwise, we do an in place update in cache.

what difference does this parameter make to Dgraph?